### ISSUE TITLE
Filter packages by maintainer name.

### ISSUE THREAD

**Issue by wlwl2** [pulsar-edit/package-backend#1]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Currently Atom does not allow us to filter search results by maintainer name.

### Enter your response below:

This would allow package maintainers to find their own packages quickly. My guess is that they would usually make
tools that they are using themselves to solve a problem that they've found. This benefits the rest of the community as they do not have to go through the same mistakes as that maintainer.

### Any alternatives?

None that I can think of now.

**Comment by confused-Techie** [comment]
I've transferred this issue over to the backend repo, as that functionality would have to made available here first. I think this is a totally fine idea, and see no issue with implementing it. 

Although as a reminder any enhancements to the Backend API are awaiting a 2.0 release as per the plan of the backend, which you can see more details in the readme of this repo. 

Otherwise I'll go ahead and add that to the [Backend Roadmap](https://github.com/orgs/pulsar-edit/projects/2).

Thanks for the contribution!

**Comment by wlwl2** [comment]
> I am having trouble understanding exactly what you mean. For installed community packages, Atom does filter out search results if you input the package author's name.

This would be in the Atom editor (Install package search). Sorry I forgot to clarify, however, I do not use the website anymore now since the images were not working a long time ago (months ago?), and now there is an increased presence of spam packages on the front page of the website.

**Comment by confused-Techie** [comment]
> > I am having trouble understanding exactly what you mean. For installed community packages, Atom does filter out search results if you input the package author's name.
> 
> This would be in the Atom editor (Install package search). Sorry I forgot to clarify, however, I do not use the website anymore now since the images were not working a long time ago (months ago?), and now there is an increased presence of spam packages on the front page of the website.
> 
> Another thing to clarify is that I consider the website and Atom Install search the similar/same things. They pull from the same source and you want to find the same package whatever that pkg may be. This may not be the direction that Pulsar is going, the website and the desktop app may differ which is fine. They might not even have an external website and solely rely on desktop to find packages- I do not know what direction they may go in the **far** future.
> 
> What I mean is that we should not only have one liner search engine. Maybe click on a button that says search by maintainer name or something.

Well to answer some of those questions.

I've moved your issue to this repo because this repo is the 'external website'. 

This repo is the API backend, that is already hosted in the cloud, that would be the service that a frontend website talks to, to find packages, as well as the editor itself, the cli and so on. This should be the single source for all of those.

Additionally while I realize that Atom's service does have broken images and many spam packages, this is our new backend. Which has been built from the ground up, and no longer contains any spam packages (as far as we are aware) and is the backend that any recent binary of the Pulsar editor will use for searching within the editor itself.

**Comment by Digitalone1** [comment]
This could be made linking packages table to users one. One to many or many to many, we have to decide.

**Comment by confused-Techie** [comment]
Resolved by #215 
The backend now supports the query parameter of `owner` which will match with the owner of the repository that's been published. For example [`https://web.pulsar-edit.dev/packages?owner=savetheclocktower`](https://web.pulsar-edit.dev/packages?owner=savetheclocktower)
