### ISSUE TITLE
`ppm` Themes searching uses different methodology than implemented

### ISSUE THREAD

**Issue by asiloisad** [pulsar-edit/package-backend#204]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The `Packages` & `Themes` buttons of `Settings/Install` doesn't have effect.

### Pulsar version

1.109.0

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Go to Settings -> Install -> type any text e.g. `Hydrogen`
2. Check switch to `Packages`
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/c9d20553-da90-48c5-afbf-326e35aac14d)
3. Check switch to `Themes`
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/42f7a2dc-5607-4dd6-a1ee-b452f84f4986)
4. Observe the results are the same, so the switch doesn't have effect

**Comment by Spiker985** [comment]
Interesting

How in the world did we not know until _now_ that the themes searching was busted in the editor? (Not blaming you, just for clarity)

We've had several people question things about custom themes and syntax highlighting before now 🤔

I wonder if people were finding the themes on the web and installing from there, installing them as github packages, or manually installing them 🤷‍♂️

But additionally, how do we prevent this regression in the future? Do we have a few static theme entries we explicitly test for? (this could balloon costs)

**Comment by confused-Techie** [comment]
@Spiker985 
We probably never noticed because searching for packages still returns themes. 

We only exclusively return themes on the themes endpoint, but the packages endpoint returns both. So you can still find themes by searching for `theme`, `syntax` or `ui`.

Otherwise it's a bit difficult to test. Since this is one of those cross-cutting concerns, where something can't really be decomposed into a test. 
Since to test something like this, we need to make sure that `settings-view` does it properly, and that `ppm` does it properly, and that `package-backend` does it properly.

I really think the best way is just having proper documentation. Since if Atom's Server Side docs had been accurate, we would have never had this issue. They simple didn't document many endpoints, and many query parameters. 

Potentially we could have PPM test hitting actual endpoints (Which it does already do a few) and one of those test for finding a specific package, and ensuring we don't find another particular package, but that isn't always the easiest. And like you said would increase costs.

Also just to mention, the website doesn't actually even support any kind of filtering, it only searches the packages endpoint, which returns everything, so it's just as if you searched only packages in the settings UI.

I feel like the best step to fixing this would be to reduce the amount of 'hops' involved in this logic, such as moving PPM into core, or having `settings-view` make requests like this one itself, rather than shelling out to PPM. But not sure if that's totally worth it, as it would still have to shell out for many other tasks, at least until we fully move PPM into core.

**Comment by Spiker985** [comment]
Yeah, while trying to debug this I was consistently confused by seeing zero network traffic (outside of user icons) inside the dev tools - I actually hadn't realized it was shelling out to ppm to begin without

Something I do worry about (not necessarily regarding this particular issue itself, but for Pulsar as a whole) is the security risks involved with the outdated-ness of the editor coupled with web requests

It's arguably something we're working towards overall, but still - makes me think sometimes. Specifically, it makes me wonder if they tried to keep as many "web" calls relegated to ppm, so as not to treat the editor (which is basically a mini web browser) as an actual web browser
