### ISSUE TITLE
[BUG] Archive and mark as broken `linter-remark` package

### ISSUE THREAD

**Issue by AlexWayfer** [pulsar-edit/package-backend#212]
**Is this Bug Present in the upstream API Server?**
- [x] Yes
- [ ] No
- [ ] Unsure

**What is the Bug**

Please, mark as archived and broken the `linter-remark` package.

https://web.pulsar-edit.dev/packages/linter-remark

https://github.com/wooorm/linter-remark

**How to Replicate the Bug**

Just open the page. You can install the package without notices, but it won't work, also the repo is archived.

**Comment by confused-Techie** [comment]
Thanks @AlexWayfer for pointing this out!

It looks like for some reason the author has decided to go as far as deleted all code files from the repo, notice how the repository currently only has a `readme.md` and `package.json`. 

Very curious, but I can absolutely go ahead and add the correct badges to this package, but since you discovered it, do you think there's any value in this package being forked by [`pulsar-cooperative`](https://github.com/pulsar-cooperative]?

**Comment by AlexWayfer** [comment]
> Thanks @AlexWayfer for pointing this out!
> 
> It looks like for some reason the author has decided to go as far as deleted all code files from the repo, notice how the repository currently only has a `readme.md` and `package.json`.
> 
> Very curious, but I can absolutely go ahead and add the correct badges to this package, but since you discovered it, do you think there's any value in this package being forked by [`pulsar-cooperative`](https://github.com/pulsar-cooperative)?

Oh yeah. By me it'd be very valued. It's a simple and popular linter for Markdown, as well as Stylelint or ESLint for their types. Probably, not an easy with their plugins and configs systems, as well as other mentioned linters, but… we (almost) all write Markdowns, and I like linters.

Unfortunately, I'm not too good with Atom (Pulsar) packages, so I'm lazy to learn a lot of new stuff to refresh this package in a fork.

The main problem, I guess, that `remark` moved to ESM, with which, as we know, Electron had problems.

And I've checked existing forks and packages and found nothing similar. I've found the [`remark`](https://web.pulsar-edit.dev/packages/remark) package, didn't try it, but it seems like prettier instead of linter + less configurable.
