### ISSUE TITLE
Archive tag for asciidoctor packages

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/package-backend#262]
All packages published by asciidoctor appear to have been archived 28/12/22:

[asciidoc-preview](https://web.pulsar-edit.dev/packages/asciidoc-preview) - https://github.com/asciidoctor/atom-asciidoc-preview
[language-asciidoc](https://web.pulsar-edit.dev/packages/language-asciidoc) - https://github.com/asciidoctor/atom-language-asciidoc
[autocomplete-asciidoc](https://web.pulsar-edit.dev/packages/autocomplete-asciidoc) - https://github.com/asciidoctor/atom-autocomplete-asciidoc
[asciidoc-image-helper](https://web.pulsar-edit.dev/packages/asciidoc-image-helper) - https://github.com/asciidoctor/atom-asciidoc-image-helper
[asciidoc-assistant](https://web.pulsar-edit.dev/packages/asciidoc-assistant) - https://github.com/asciidoctor/atom-asciidoc-assistant

The first on the list seems to also be broken but there is also a request open on pulsar-cooperative to fork that package - https://github.com/pulsar-cooperative/.github/issues/3

**Comment by ianwillie** [comment]
I am adding this comment which is taken from https://github.com/pulsar-edit/pulsar/issues/256 I don't know the best place to put it for now.

Hi Folks, I commented in a few posts earlier in May that I thought the way to go would be to modify pulsar markdown-preview to preview asciidoctor. Markdown-preview is an uptodate expertly maintained pulsar bundled package. All that is needed is to adapt it to render the preview using asciidoctor.js which is  maintained by asciidoctor.org and relieves pulsar team of that burden. atom-asciidoctor-preview is no longer maintained by asciidoctor.org and I think maintenance will be more difficult than that just suggested.

Well, I have had success in  adapting [markdown-preview ](https://github.com/pulsar-edit/pulsar/tree/master/packages/markdown-preview)in two different versions 1. which previews only asciidoc files with extensions like .adoc & .ad & 2. a different version which will preview both markdown and asciidoc files. 

1.https://github.com/ianwillie/IansascidocPreviewFrommarkdownpreviewnomd/tree/releaseCandidateV0.1.0# on  branch: releaseCandidateV0.1.0 branch: releaseCandidateV0.1.0  (NOT main)
https://github.com/ianwillie/IansascidocPreviewFrommarkdownpreviewnomd/archive/refs/heads/main.zip
  Once installed preview is operated by <kbd>ctrl-alt-shft-a</kbd> and a preview in external browser <kbd>ctrl-alt-shft-f</kbd>.  NOTE that you should navigate to the "releaseCandidateV0.1.0" branch not "main" to test the package.
See the package [README.md](https://github.com/ianwillie/IansascidocPreviewFrommarkdownpreviewnomd/tree/releaseCandidateV0.1.0#) for fuller details.

2. https://github.com/ianwillie/IansascidocPreviewFrommarkdownpreview    (note same url as above less terminal "nomd")
   Once installed <kbd>ctrl-alt-shft-m</kbd>  will operate the preview.  Details are in the [README.md](https://github.com/ianwillie/IansascidocPreviewFrommarkdownpreview#).

This is very much an alpha  proof of concept and the asciidoc only version is fully functional for me in daily use, the other is more buggy but works for me too. I will keep developing these but the recent admirable  modernising changes in markdown-preview to the language tools ([introduced in version 1.117.0](https://github.com/pulsar-edit/pulsar/blob/master/CHANGELOG.md#11170)) to update them to treesitter versions & speeding up buffer rendering have proved incompatible with my packages (based on version 1.116.0) for the moment. I will incorporate these changes when I learn more about treesitter language tools.  Nonetheless, these two packages presented here based on v1.116.0 work fine for me.

One caveat - this is my second experience of adapting and publishing a package, so there are very many rough edges. These are commented on in the READMEs and  the spec tests wait to be adapted to these packages and do not work.
In particular I know how to use local git but getting it all into github in a way that can be downloaded is still a bit of a mystery for me.  If anyone sends me pull requests that will be a deepening mystery, for now anyroads.

I am not sure how you would install these packages because they are modified from a core pulsar package which is bundled and I could not fork them from the original. I suggest download the zip file, extract and put a link ```IansascidocPreviewFrommarkdownpreviewnomd``` in the ```pulsar/packages``` from the directory to the unzipped ```IansascidocPreviewFrommarkdownpreviewnomd``` which contains the source code.  I work in Manjaro linux so some alterations to the code may be needed for your operating system.  The code itself is scattered with comments and commented out sections from the original markdown-preview. There quite a few console.log(): they are verbose but harmless and may help with debugging.

I guess that I should probably put this post somewhere else and there are comments on Discord about the process of maintaining atom-asciidoc-review: https://discord.com/channels/992103415163396136/996581846286618694/1255084745956655146 

Many thanks to all of you who have helped me get so far, and encouraged me. Ian
EDITED: to clarify  details & add links.

**Comment by confused-Techie** [comment]
@ianwillie I appreciate you posting about your adventures in adapting this package.

I eagerly await being able to install it from the Pulsar Package Backend, and will be more than happy to assist through that process once you're able to get everything onto GitHub!

As the original issue this request points out is being resolved, I wanted to give you a heads up this issue will close as well. But did want to take the chance to let you know that once you've gotten things settled, make sure to let me know, and we can officially refer to your package as the alternative to the one's I'm badging on this issue, so that the right users can find your awesome work.

Good luck, and thanks for the update!
